on:
  push:
    branches:
    - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/playwright-github-action@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'
      - uses: dschep/install-pipenv-action@v1

      - run: pipenv install
      - run: cd test/realworld_example && pytest login_tests.py article_tests.py registration_tests.py --headful --alluredir=./allure-results -n 1
      - run: allure generate

      - uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshot*.png

      - uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: ./allure-report/