name: Playwright E2E Tests

on:
  push:
    branches:
    - master

jobs:
  e2e-tests:
#    runs-on: python-3.6-alpine
#    steps:
#      - name: Install Requirements
#        run: apk add --update nodejs npm openjdk8 && npm install -g allure-commandline

    runs-on: ubuntu-latest # ubuntu-latest or macos-latest, windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/playwright-github-action@v1

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install -g allure-commandline
      - run: allure --version

      - name: Set Up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.7

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Run Tests
        run: |
          pipenv install --dev
          pipenv run python -m playwright install
          mkdir -p test/screenshots
          mkdir -p test/video
          cd test/
          pipenv run pytest login_tests.py --alluredir=./allure-results
          allure generate

      - uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: ./screenshots/*.png

      - uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: ./allure-report/