name: Playwright Tests Example

on:
  push:
    branches:
    - master

jobs:
  e2e-tests:
    runs-on: macos-latest # ubuntu-latest or macos-latest, windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/playwright-github-action@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Run tests
        run: |
          pipenv install --dev
          cd test/realworld_example
          pipenv run pytest login_tests.py --alluredir=./allure-results
          pipenv run allure generate

#      - name: Install dependencies and run tests
#        run: |
#          python -m pip install --upgrade pip
#          pip install pipenv
#          pipenv install --dev
#          pytest test/realworld_example/login_tests.py test/realworld_example/article_tests.py test/realworld_example/registration_tests.py --headful --alluredir=./allure-results -n 1
#          allure generate

      - uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: ./screenshots/*.png

      - uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: ./allure-report/